model:
  _target_: src.models.timmCls.TimmClassifier
  num_classes: 17
  optimizer: ${optimizer}
  scheduler: ${oc.select:scheduler, null}

  backbone:
    _target_: timm.create_model
    model_name: resnet34
    num_classes: ${..num_classes}
    pretrained: true