defaults:
  - data: data
  - model: resnet50
  - train: trainer
  - optimizer: adam
  - scheduler: cos_lr
  - callback:
    - early_stopping
    - lr_monitor
  - logger: wandb
  - infer: infer

fold: null
fold_suffix: "" 

cv_ensure: false
ensemble_ensure: false